### ISSUE TITLE
Cannot create environment in vagrant (same problem #1, different error)

### ISSUE THREAD

**Issue by jgomo3** [UtahDave/salt-vagrant-demo#10]
After `vagrant up` i get the following Error:

```
$ vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion1' up with 'virtualbox' provider...
Bringing machine 'minion2' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'ubuntu/trusty64' could not be found.

salt provisioner:
* You must include both public and private keys.
```

**Comment by danielrmeyer** [comment]
I just tried this today and get a very similar error:
vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion1' up with 'virtualbox' provider...
Bringing machine 'minion2' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

salt:
- You must include both public and private keys.

**Comment by cblument** [comment]
Recieved the same error:

Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion1' up with 'virtualbox' provider...
Bringing machine 'minion2' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

salt:
- You must include both public and private keys.
