### ISSUE TITLE
Adding pillar dir

### ISSUE THREAD

**Issue by normanrz** [UtahDave/salt-vagrant-demo#17]
I really like the Getting Started Guide. It's a lot of fun to learn Salt interactively.

In https://docs.saltstack.com/en/getstarted/config/pillar.html I got confused because the pillar directory was not synced to the master vm. Maybe this could be included in this demo repo?

**Comment by Granjow** [comment]
Same here. The user has two options, the first one is adding the pillar directory to the `Vagrant` file after it has been created locally by the user, and then re-starting the VMs:

```
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define :master do |master_config|
    master_config.vm.box = "ubuntu/trusty64"
    master_config.vm.host_name = 'saltmaster.local'
    master_config.vm.network "private_network", ip: "192.168.50.10"
    master_config.vm.synced_folder "saltstack/salt/", "/srv/salt"
    master_config.vm.synced_folder "saltstack/pillar/", "/srv/pillar" # <- add this line
[snip]
```

Or, tell the user that the file has to be created _on master_ with vim or whatever.

**Comment by UtahDave** [comment]
The pillar directory is now synced:

https://github.com/UtahDave/salt-vagrant-demo/blob/7a240d65d6382bd2eeab8988107bcbf8fcd2003b/Vagrantfile#L16

So I'm going to close this.  Thanks for the input!
