### ISSUE TITLE
Ubuntu Trusty "vagrant" package out-of-date

### ISSUE THREAD

**Issue by shorawitz** [UtahDave/salt-vagrant-demo#19]
For testing...

Ubuntu Trusty (and derivatives) should install Vagrant from https://www.vagrantup.com/downloads instead of the defined PPA.  The Trusty version fails with:

The box 'ubuntu/trusty64' could not be found.

Latest Vagrant doesn't have this issue

**Comment by UtahDave** [comment]
I think the docs have been updated to have people install from vagrantup.com so I'm going to close this issue now. Please feel free to comment here if this needs to be reopened.

Thanks!
