### ISSUE TITLE
Doc suggestion

### ISSUE THREAD

**Issue by shorawitz** [UtahDave/salt-vagrant-demo#20]
For dunderheads like me, maybe you could add a line to remind the newbie to make sure VT is turned on in the BIOS.  I installed this on an old(ish) Core-i7 test server I had (which used to run my VB vm's) and somehow the BIOS setting for VT was disabled.

The master never booted and vagrant was timing out.  Big clue, VB would only allow me to create 32-bit VM's.  Once I loaded the VB GUI and saw that, I knew what the problem was.

**Comment by UtahDave** [comment]
Would you mind opening a pull request with the documentation you'd like to see?
