### ISSUE TITLE
use the new repo.saltstack.com repos from the start

### ISSUE THREAD

**Issue by TheBigBear** [UtahDave/salt-vagrant-demo#22]
I think it would be great for this "Getting started guide" environment, if it stayed more up-to-date and was actually using & tracking the new saltstack ubuntu repos from repo.saltstack.com?

It somehow feels strange to have a "getting started guide" environment that uses an old release as the basis.

@eliasp can probably fill in the required ubuntu lines for the Vagrantfile ? ( https://github.com/saltstack-formulas/salt-formula/issues/180 )

**Comment by UtahDave** [comment]
@TheBigBear the VMs in this demo use the standard bootstrap script and use the packages from repo.saltstack.com now.  Can we close this issue?

**Comment by TheBigBear** [comment]
@UtahDave great work. yes, I think this takes care of this one. well done.
