### ISSUE TITLE
Missing directory

### ISSUE THREAD

**Issue by spuder** [UtahDave/salt-vagrant-demo#23]
Not sure where to open this issue. The [getting started documentation](https://docs.saltstack.com/en/getstarted/fundamentals/states.html) says

> To simplify things, our Vagrant file maps the /srv/salt folder on your Salt master to the local salt-vagrant-demo-master/saltstack/salt

Yet /srv/salt/saltstack directory doesn't exist inside the vagrant VM

**Comment by UtahDave** [comment]
I just tested this and it's works for me:

```
vagrant@saltmaster:~$ ls /srv/salt/
common  top.sls
```

Are you still having this issue? Have you made any changes to the Vagrantfile?

**Comment by UtahDave** [comment]
I've tested this again and the directory is still correctly mapped. Since I haven't heard back I'm going to close this issue. Please feel free to comment here if you're still seeing this issue and we're reopen.

Thanks!
