### ISSUE TITLE
Only 1 minion can be ping(ed) sometimes

### ISSUE THREAD

**Issue by tovin07** [UtahDave/salt-vagrant-demo#29]
After vagrant up, I ssh to the salt master and run: `salt "*" test.ping`, then I got this:

``` bash
root@saltmaster:/srv/salt# salt "*" test.ping
minion1:
    True
minion2:
    Minion did not return. [No response]
```

I've tried this 20 times (restart, vagrant up, ssh to master, run test.ping), 2 minions return ping True only 2 times.

After vagrant up, my computer still have 3GB free of RAM, 50GB HDD free.

**Comment by UtahDave** [comment]
I'm having trouble reproducing this with the latest changes from the repo.

Can you try running this again after verifying you're using the very latest code from this repo? I just ran a test.ping 20 times and I got responses from both minions every time. We did make a couple changes yesterday that did improve the responsiveness of the salt master.

**Comment by tovin07** [comment]
I cannot re-produce this issues today.

Thank you! 😃

**Comment by h12w** [comment]
I had the same issue too. Either minion1 or minion2 randomly failed to return.
It seems to be related to "ubuntu/trusty64" because after I changed xxx.vm.box to "bento/centos-7.2" in Vagrantfile, it just works smoothly.
