### ISSUE TITLE
Vagrant Up Fails

### ISSUE THREAD

**Issue by Blitz2145** [UtahDave/salt-vagrant-demo#32]
Trying to run this environment but the `vagrant up` command fails with the following output. 

Output of `vagrant up` command:
https://gist.github.com/Blitz2145/6f95ea69ea839cabb66a293f46cdc91f

**Comment by Blitz2145** [comment]
Seems to be caused by the following:

https://github.com/mitchellh/vagrant/issues/8005

I've downgraded to v1.8.6 of vagrant and its working now.

**Comment by UtahDave** [comment]
Thanks for letting me know!  I'll keep an eye on that issue and leave this issue open until fixed.

**Comment by UtahDave** [comment]
Looks like this was fixed via https://github.com/mitchellh/vagrant/pull/7986 I'm not sure when the next release is expected.

**Comment by UtahDave** [comment]
@Blitz2145 

Vagrant version 1.9.0 has been released. https://www.vagrantup.com/downloads.html

I just tested with Vagrant 1.9.0 and everything seemed to work fine.

Can you test with 1.9.0 and let me know if we can close this issue? 

Thanks!

**Comment by Blitz2145** [comment]
Will do later thanks!

**Comment by Blitz2145** [comment]
@UtahDave Confirmed, the bug has been fixed. Provisioned the demo env no problem.

**Comment by UtahDave** [comment]
Thanks, @Blitz2145 !
