### ISSUE TITLE
[Help] i can't install salt demo on my MAC, Provison Salt failed with logs

### ISSUE THREAD

**Issue by peter-zyj** [UtahDave/salt-vagrant-demo#4]
Hi, David
After much Adjustment on VirtualBox 5.0 and its Guest Addition verison match on My Mac, i touch the steps of "Salt Provision", but error coming again with the log::

==> master: Running provisioner: salt...
Copying salt master config to vm.
Checking if salt-master is installed
salt-master was not found.
/opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/salt/provisioner.rb:154:in `%': can't convert Vagrant::Config::V2::DummyConfig to Array (Vagrant::Config::V2::DummyConfig#to_ary gives Vagrant::Config::V2::DummyConfig) (TypeError)
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/salt/provisioner.rb:154:in`bootstrap_options'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/salt/provisioner.rb:236:in `run_bootstrap_script'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/plugins/provisioners/salt/provisioner.rb:9:in`provision'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in`call'
    from /opt/vagrant/embedded/gems/gems/vagrant-1.7.3/lib/vagrant/action/warden.rb:34:in `call'

could you please help me for this?! 

thansk
/Carl

**Comment by n0ndual** [comment]
i have the same problem.

**Comment by UtahDave** [comment]
Hm. I haven't tested this on a Mac. Let me have a coworker give it a try.

I do know there were several bugs with Vagrant when using VirtualBox 5.0.

Thanks for the reports

**Comment by UtahDave** [comment]
Could you try uninstalling VirtualBox 5.0 and installing 4.3?  I think vagrant hasn't caught up to the latest changes in VirtualBox 5.0 yet.

**Comment by UtahDave** [comment]
OK, this is a known problem with Vagrant 1.7.3, which has been fixed with this PR  https://github.com/mitchellh/vagrant/pull/5936

So for now, downgrading to Vagrant 1.7.2 or waiting until that fix makes it into a release will solve this problem.

Feel free to comment here if we should open this back up, but this appears to be a Vagrant issue.

Thanks!
