### ISSUE TITLE
Host-only network does not allow communication between master and minions

### ISSUE THREAD

**Issue by faulesocke** [UtahDave/salt-vagrant-demo#40]
The VirtualBox provider by default creates a host-only network per machine, as documented here: https://www.vagrantup.com/docs/virtualbox/networking.html

Therefore communication between the virtual machines is not possible. To fix the issue, just modify the vm.network calls to use a virtualbox internal network, for example:

`master_config.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "minionnet"`

**Comment by UtahDave** [comment]
@faulesocke, are you sure?  The virtual machines can and do communicate with each other in my testing.

**Comment by UtahDave** [comment]
@faulesocke are you still seeing this behavior? I can't reproduce. After spinning up the VMs they do communicate.

**Comment by UtahDave** [comment]
I think this may have been an issue with networking on your box. I'm going to close this for now since I haven't heard back.

If anyone continues to run into this issue, please comment here and I'll happily reopen.

Thanks!
