### ISSUE TITLE
Error while excuting 'VBoxManage'

### ISSUE THREAD

**Issue by bytemarcz** [UtahDave/salt-vagrant-demo#44]
Hello, 

I'm running into an issue when I run vagrant up. It appears to fail when it reaches either the master or minion 1. I was only able to start the master virtual machine twice, but the same output occurs when it gets to minion 1. I'm running vagrant version 2.1.14 and virtual box version 5.12.18. Any help would  be great. 

C:\Users\marzamor\salt\salt-vagrant-demo-master> vagrant up
C:/Users/marzamor/salt/salt-vagrant-demo-master/Vagrantfile:5: warning: already initialized constant VAGRANTFILE_API_VERSION
C:/Users/marzamor/salt/salt-vagrant-demo-master/Vagrantfile:5: warning: previous definition of VAGRANTFILE_API_VERSION was here
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion1' up with 'virtualbox' provider...
Bringing machine 'minion2' up with 'virtualbox' provider...
==> master: Importing base box 'bento/ubuntu-16.04'...
==> master: Matching MAC address for NAT networking...
==> master: Checking if box 'bento/ubuntu-16.04' is up to date...
==> master: Setting the name of the VM: master
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 (guest) => 2222 (host) (adapter 1)
==> master: Running 'pre-boot' VM customizations...
==> master: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "a9aacfe4-0749-4b2b-912e-941e946abbc6", "--type", "headless"]

Stderr: VBoxManage.exe: error: The virtual machine 'master' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\marzamor\VirtualBox VMs\master\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

**Comment by maczamora** [comment]
As a side note, I re-installed vbox and run powershell as admin and the same issue occurs on minion 1. Master appears to load successfully, but after destroying and running vagrant up it fails again.

**Comment by UtahDave** [comment]
I can't reproduce this.

Does this discussion help at all?  https://github.com/hashicorp/vagrant/issues/8687

**Comment by bytemarcz** [comment]
Hi @UtahDave, I will look at what you suggested and follow up.

**Comment by UtahDave** [comment]
@maczamora Are you still running into this issue?

**Comment by bytemarcz** [comment]
This can be closed, I gave up and ran docker containers..
