### ISSUE TITLE
BOOTSTRAP Failure :  * ERROR: Option does not exist : x

### ISSUE THREAD

**Issue by fewknow** [UtahDave/salt-vagrant-demo#54]
sing Bootstrap Options:  -P -c /tmp -x python3 -c /tmp -M -N stable
Bootstrapping Salt... (this may take a while)

 * ERROR: Option does not exist : x
  Usage :  bootstrap-salt.sh [options] <install-type> <install-type-args>

  Installation types:
    - stable (default)
    - daily  (ubuntu specific)
    - git

  Examples:
    $ bootstrap-salt.sh
    $ bootstrap-salt.sh stable
    $ bootstrap-salt.sh daily
    $ bootstrap-salt.sh git
    $ bootstrap-salt.sh git develop
    $ bootstrap-salt.sh git 8c3fadf15ec183e5ce8c63739850d543617e4357

  Options:
  -h  Display this message
  -v  Display script version
  -n  No colours.
  -D  Show debug output.
  -c  Temporary configuration directory
  -M  Also install salt-master
  -S  Also install salt-syndic
  -N  Do not install salt-minion
  -C  Only run the configuration function. This option automaticaly
      bypasses any installation.
  -P  Allow pip based installations. On some distributions the required salt
      packages or it's dependencies are not available as a package for that
      distribution. Using this flag allows the script to use pip as a last
      resort method. NOTE: This works for functions which actually implement
      pip based installations.
  -F  Allow copied files to overwrite existing(config, init.d, etc)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/tmp/bootstrap_salt.sh  -P -c /tmp -x python3 -c /tmp -M -N stable

Stdout from the command:

  Usage :  bootstrap-salt.sh [options] <install-type> <install-type-args>

  Installation types:
    - stable (default)
    - daily  (ubuntu specific)
    - git

  Examples:
    $ bootstrap-salt.sh
    $ bootstrap-salt.sh stable
    $ bootstrap-salt.sh daily
    $ bootstrap-salt.sh git
    $ bootstrap-salt.sh git develop
    $ bootstrap-salt.sh git 8c3fadf15ec183e5ce8c63739850d543617e4357

  Options:
  -h  Display this message
  -v  Display script version
  -n  No colours.
  -D  Show debug output.
  -c  Temporary configuration directory
  -M  Also install salt-master
  -S  Also install salt-syndic
  -N  Do not install salt-minion
  -C  Only run the configuration function. This option automaticaly
      bypasses any installation.
  -P  Allow pip based installations. On some distributions the required salt
      packages or it's dependencies are not available as a package for that
      distribution. Using this flag allows the script to use pip as a last
      resort method. NOTE: This works for functions which actually implement
      pip based installations.
  -F  Allow copied files to overwrite existing(config, init.d, etc)

Stderr from the command:

 * ERROR: Option does not exist : x

**Comment by UtahDave** [comment]
Thanks for the report.  Testing now.

**Comment by UtahDave** [comment]
Can you try this again? I think there was an issue with the bootstrap script itself that has been resolved.

vagrant up worked for me.

**Comment by UtahDave** [comment]
Any update on this?  I believe this was an upstream bootstrap issue that was fixed. 

Let me know if you're still running into this problem.
