### ISSUE TITLE
salt-vagrant-demo password?

### ISSUE THREAD

**Issue by makeitstatic** [UtahDave/salt-vagrant-demo#57]
While following the instructions on the getting started guide, I am at a step after I run "vagrant up" in Powershell.
When I execute the command, "vagrant ssh master", I am asked for a password.
I am lost as to what this password must be.
Please specifiy?

**Comment by makeitstatic** [comment]
The username and password to vagrant virtual environments is: "vagrant", "vagrant".

**Comment by UtahDave** [comment]
Yes, "vagrant", "vagrant" is the password, but usually when I run "vagrant ssh master" I'm dropped directly into the terminal in the salt master vm.

I'll do some testing to see if I can reproduce this.

Are you running this on Windows?

**Comment by UtahDave** [comment]
I can't reproduce this and I haven't heard back since March, so I'm going to assume you resolved your issue. Please feel free to reopen an issue if you come across this again.

Thanks!
