### ISSUE TITLE
Vagrant File network settings

### ISSUE THREAD

**Issue by najnuk86** [UtahDave/salt-vagrant-demo#58]
The network settings in the Vagrant File is not working for mac users. I think there was a wrong commit made to it on the network configuration

  net_ip = "192.168.50"

The vagrant error shows it has to be  56.0/21 so please change the VagrantFile to have the right IP range 

correct one  

  net_ip = "192.168.56"

**Comment by UtahDave** [comment]
Have you tested it with that change?

Can you copy and paste the exact error output you're seeing?

Thanks!

**Comment by SquareByte** [comment]
I do not see that IP stump, but an added .1. Though I also have an error during `vagrant up` after a fresh clone of this repo:

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "vboxnet3", "--ip", "192.168.50.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
```

vagrant: 2.2.6
virtualbox: 6.1.32_Ubuntu r149290
OS: Tuxedo (basically an Ubuntu 22/04)

**Comment by najnuk86** [comment]
@UtahDave 

If we the ip range is on 192.168.50 i get the following error. 

> ababu@ZALANDO-61522 salt-vagrant-demo % vagrant up
> Bringing machine 'master' up with 'virtualbox' provider...
> Bringing machine 'minion1' up with 'virtualbox' provider...
> Bringing machine 'minion2' up with 'virtualbox' provider...
> ==> master: Checking if box 'generic/ubuntu2004' version '3.6.14' is up to date...
> ==> master: Clearing any previously set forwarded ports...
> ==> master: Clearing any previously set network interfaces...
> The IP address configured for the host-only network is not within the
> allowed ranges. Please update the address used to be within the allowed
> ranges and run the command again.
> 
>   Address: 192.168.50.10
>   Ranges: 192.168.56.0/21
> 
> Valid ranges can be modified in the /etc/vbox/networks.conf file. For
> more information including valid format see:
>   https://www.virtualbox.org/manual/ch06.html#network_hostonly
> ababu@ZALANDO-61522 salt-vagrant-demo % vi Vagrantfile 
> ababu@ZALANDO-61522 salt-vagrant-demo % grep "net_ip =" Vagrantfile 
>   net_ip = "192.168.50"
> ababu@ZALANDO-61522` salt-vagrant-demo %

After changing the net_ip value to "192.168.56." the issue is resolved and vagrant is getting nodes up and running. 

> I'm using an Intel MacBook Pro.

Regards,
Akhilesh

**Comment by UtahDave** [comment]
Have you made changes to your networking in virtualbox?

Also, you might try upgrading vagrant as well.

**Comment by UtahDave** [comment]
Hm. I just upgraded my virtualbox install.  I had 5.x and I upgraded to 6.1.x  (latest) and I'm getting the same error as you.

**Comment by UtahDave** [comment]
Virtualbox 6.1.x defaults to a `192.168.56` ip address range. 

I just pushed the fix for this.

Thanks @najnuk86 for reporting this!

**Comment by najnuk86** [comment]
@UtahDave : You are welcome :)

**Comment by SquareByte** [comment]
This fixes it also for my case. Thank you.
