### ISSUE TITLE
vagrant up step fails on mac osx 10.7.5

### ISSUE THREAD

**Issue by rduggal** [UtahDave/salt-vagrant-demo#7]
Trying to get the demo going as per README.rst, I get a failure, captured output below.

Any idea what could i be doing wrong ?

---

bash-3.2# vagrant up
Bringing machine 'master' up with 'virtualbox' provider...
Bringing machine 'minion1' up with 'virtualbox' provider...
Bringing machine 'minion2' up with 'virtualbox' provider...
==> master: Importing base box 'ubuntu/trusty64'...
==> master: Matching MAC address for NAT networking...
==> master: Checking if box 'ubuntu/trusty64' is up to date...
==> master: Setting the name of the VM: salt-vagrant-demo_master_1437800690447_95469
==> master: Clearing any previously set forwarded ports...
==> master: Fixed port collision for 22 => 2222. Now on port 2200.
==> master: Clearing any previously set network interfaces...
==> master: Preparing network interfaces based on configuration...
    master: Adapter 1: nat
    master: Adapter 2: hostonly
==> master: Forwarding ports...
    master: 22 => 2200 (adapter 1)
==> master: Booting VM...
==> master: Waiting for machine to boot. This may take a few minutes...
    master: SSH address: 127.0.0.1:2200
    master: SSH username: vagrant
    master: SSH auth method: private key
    master: Warning: Connection timeout. Retrying...
    master: Warning: Remote connection disconnect. Retrying...
    master: 
    master: Vagrant insecure key detected. Vagrant will automatically replace
    master: this with a newly generated keypair for better security.
    master: 
    master: Inserting generated public key within guest...
    master: Removing insecure key from the guest if it's present...
    master: Key inserted! Disconnecting and reconnecting using new SSH key...
==> master: Machine booted and ready!
==> master: Checking for guest additions in VM...
==> master: Setting hostname...
==> master: Configuring and enabling network interfaces...
==> master: Mounting shared folders...
    master: /vagrant => /Users/rama/salt-vagrant-demo
    master: /srv/salt => /Users/rama/salt-vagrant-demo/saltstack/salt
==> master: Running provisioner: salt...
Copying salt master config to vm.
Uploading master keys.
Checking if salt-master is installed
salt-master was not found.
Using Bootstrap Options:  -k /tmp/minion-seed-keys -M -N stable
Bootstrapping Salt... (this may take a while)
stdin: is not a tty

%

T
o
t
a
l

% Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

0

0

0
     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

0

   0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
-  INFO:  sh -- Version 2015.07.22
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.13.0-55-generic
-  INFO:   Distribution: Ubuntu 14.04
-  INFO: Installing master

9
3

2
0
4
k
   93  191k    0     0  82547      0  0:00:02  0:00:02 --:--:-- 82517

1
0
0  204k  100  204k    0     0  87900      0  0:00:02  0:00:02 --:--:-- 87871
-  INFO: Found function install_ubuntu_stable_deps
-  INFO: Found function preseed_master
-  INFO: Found function install_ubuntu_stable
-  INFO: Found function install_ubuntu_restart_daemons
-  INFO: Found function daemons_running
-  INFO: Found function install_ubuntu_check_services
-  INFO: Running install_ubuntu_stable_deps()
  Ign http://archive.ubuntu.com trusty InRelease
  Ign http://security.ubuntu.com trusty-security InRelease
  Ign http://archive.ubuntu.com trusty-updates InRelease
  Hit http://archive.ubuntu.com trusty Release.gpg
  Get:1 http://security.ubuntu.com trusty-security Release.gpg [933 B]
  Get:2 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
  Get:3 http://security.ubuntu.com trusty-security Release [63.5 kB]
  Hit http://archive.ubuntu.com trusty Release
  Get:4 http://archive.ubuntu.com trusty-updates Release [63.5 kB]
  Get:5 http://security.ubuntu.com trusty-security/main Sources [88.7 kB]
  Get:6 http://archive.ubuntu.com trusty/main Sources [1,064 kB]
  Get:7 http://security.ubuntu.com trusty-security/universe Sources [28.1 kB]
  Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [315 kB]
  Get:9 http://security.ubuntu.com trusty-security/universe amd64 Packages [111 kB]
  Get:10 http://security.ubuntu.com trusty-security/main Translation-en [169 kB]
  Get:11 http://security.ubuntu.com trusty-security/universe Translation-en [64.0 kB]
  Get:12 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]
  Hit http://archive.ubuntu.com trusty/main amd64 Packages
  Hit http://archive.ubuntu.com trusty/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty/main Translation-en
  Hit http://archive.ubuntu.com trusty/universe Translation-en
  Get:13 http://archive.ubuntu.com trusty-updates/main Sources [223 kB]
  Get:14 http://archive.ubuntu.com trusty-updates/universe Sources [127 kB]
  Get:15 http://archive.ubuntu.com trusty-updates/main amd64 Packages [584 kB]
  Get:16 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [297 kB]
  Get:17 http://archive.ubuntu.com trusty-updates/main Translation-en [281 kB]
  Get:18 http://archive.ubuntu.com trusty-updates/universe Translation-en [157 kB]
  Ign http://archive.ubuntu.com trusty/main Translation-en_US
  Ign http://archive.ubuntu.com trusty/universe Translation-en_US
  Fetched 10.0 MB in 1min 9s (144 kB/s)
  Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...

The following NEW packages will be installed:
  debian-archive-keyring
0 upgraded, 1 newly installed, 0 to remove and 52 not upgraded.
Need to get 34.4 kB of archives.
After this operation, 84.0 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe debian-archive-keyring all 2012.4 [34.4 kB]
Fetched 34.4 kB in 1s (30.0 kB/s)
Selecting previously unselected package debian-archive-keyring.
(Reading database ... 86712 files and directories currently installed.)
Preparing to unpack .../debian-archive-keyring_2012.4_all.deb ...
Unpacking debian-archive-keyring (2012.4) ...
Setting up debian-archive-keyring (2012.4) ...
Ign http://security.ubuntu.com trusty-security InRelease
Ign http://archive.ubuntu.com trusty InRelease
Hit http://security.ubuntu.com trusty-security Release.gpg
Ign http://archive.ubuntu.com trusty-updates InRelease
Hit http://security.ubuntu.com trusty-security Release
Hit http://archive.ubuntu.com trusty Release.gpg
Hit http://archive.ubuntu.com trusty-updates Release.gpg
Hit http://security.ubuntu.com trusty-security/main Sources
Hit http://archive.ubuntu.com trusty Release
Hit http://security.ubuntu.com trusty-security/universe Sources
Hit http://archive.ubuntu.com trusty-updates Release
Hit http://security.ubuntu.com trusty-security/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/main Sources
Hit http://archive.ubuntu.com trusty/universe Sources
Hit http://security.ubuntu.com trusty-security/main Translation-en
Hit http://archive.ubuntu.com trusty/main amd64 Packages
Hit http://security.ubuntu.com trusty-security/universe Translation-en
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Hit http://archive.ubuntu.com trusty/main Translation-en
Hit http://archive.ubuntu.com trusty/universe Translation-en
Hit http://archive.ubuntu.com trusty-updates/main Sources
Hit http://archive.ubuntu.com trusty-updates/universe Sources
Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
Hit http://archive.ubuntu.com trusty-updates/main Translation-en
Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
Ign http://archive.ubuntu.com trusty/main Translation-en_US
Ign http://archive.ubuntu.com trusty/universe Translation-en_US
Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...
software-properties-common is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 52 not upgraded.
-  INFO: Installing Python Requests/Chardet from Chris Lea's PPA repository
  gpg:
  keyring `/tmp/tmpq__j495u/secring.gpg' created
  gpg:
  keyring`/tmp/tmpq__j495u/pubring.gpg' created
  gpg:
  requesting key C7917B12 from hkp server keyserver.ubuntu.com
  gpg:
  /tmp/tmpq__j495u/trustdb.gpg: trustdb created
  gpg:
  key C7917B12: public key "Launchpad chrislea" imported
  gpg:
  Total number processed: 1
  gpg:               imported: 1  (RSA: 1)
  OK
  gpg:
  keyring `/tmp/tmpyz5u8lys/secring.gpg' created
  gpg:
  keyring`/tmp/tmpyz5u8lys/pubring.gpg' created
  gpg:
  requesting key C7917B12 from hkp server keyserver.ubuntu.com
  gpg: /tmp/tmpyz5u8lys/trustdb.gpg: trustdb created
  gpg: key C7917B12: public key "Launchpad chrislea" imported
  gpg: Total number processed: 1
  gpg:               imported: 1  (RSA: 1)
  OK
  Ign http://security.ubuntu.com trusty-security InRelease
  Ign http://archive.ubuntu.com trusty InRelease
  Ign http://ppa.launchpad.net trusty InRelease
  Hit http://security.ubuntu.com trusty-security Release.gpg
  Ign http://archive.ubuntu.com trusty-updates InRelease
  Hit http://security.ubuntu.com trusty-security Release
  Ign http://ppa.launchpad.net trusty InRelease
  Hit http://archive.ubuntu.com trusty Release.gpg
  Hit http://security.ubuntu.com trusty-security/main Sources
  Hit http://archive.ubuntu.com trusty-updates Release.gpg
  Hit http://security.ubuntu.com trusty-security/universe Sources
  Get:1 http://ppa.launchpad.net trusty Release.gpg [316 B]
  Hit http://security.ubuntu.com trusty-security/main amd64 Packages
  Hit http://archive.ubuntu.com trusty Release
  Get:2 http://ppa.launchpad.net trusty Release.gpg [316 B]
  Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty-updates Release
  Get:3 http://ppa.launchpad.net trusty Release [14.0 kB]
  Hit http://security.ubuntu.com trusty-security/main Translation-en
  Hit http://archive.ubuntu.com trusty/main Sources
  Hit http://security.ubuntu.com trusty-security/universe Translation-en
  Get:4 http://ppa.launchpad.net trusty Release [14.0 kB]
  Hit http://archive.ubuntu.com trusty/universe Sources
  Get:5 http://ppa.launchpad.net trusty/main amd64 Packages [1,041 B]
  Hit http://archive.ubuntu.com trusty/main amd64 Packages
  Hit http://archive.ubuntu.com trusty/universe amd64 Packages
  Get:6 http://ppa.launchpad.net trusty/main amd64 Packages [2,308 B]
  Hit http://archive.ubuntu.com trusty/main Translation-en
  Hit http://archive.ubuntu.com trusty/universe Translation-en
  Hit http://archive.ubuntu.com trusty-updates/main Sources
  Hit http://archive.ubuntu.com trusty-updates/universe Sources
  Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
  Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty-updates/main Translation-en
  Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
  Ign http://ppa.launchpad.net trusty/main Translation-en_US
  Ign http://archive.ubuntu.com trusty/main Translation-en_US
  Ign http://ppa.launchpad.net trusty/main Translation-en
  Ign http://archive.ubuntu.com trusty/universe Translation-en_US
  Ign http://ppa.launchpad.net trusty/main Translation-en_US
  Ign http://ppa.launchpad.net trusty/main Translation-en
  Fetched 32.0 kB in 12s (2,521 B/s)
  Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...

pciutils is already the newest version.
procps is already the newest version.
python-apt is already the newest version.
upstart is already the newest version.
The following extra packages will be installed:
  python-chardet
The following packages will be upgraded:
  python-chardet python-requests
2 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
Need to get 151 kB of archives.
After this operation, 9,216 B disk space will be freed.
Get:1 http://ppa.launchpad.net/chris-lea/python-chardet/ubuntu/ trusty/main python-chardet all 2.2.1-4chl1~trusty1 [107 kB]
Get:2 http://ppa.launchpad.net/chris-lea/python-requests/ubuntu/ trusty/main python-requests all 2.3.0-1chl1~trusty1 [44.3 kB]
Fetched 151 kB in 2s (55.4 kB/s)
(Reading database ... 86722 files and directories currently installed.)
Preparing to unpack .../python-chardet_2.2.1-4chl1~trusty1_all.deb ...
Unpacking python-chardet (2.2.1-4chl1~trusty1) over (2.0.1-2build2) ...
Preparing to unpack .../python-requests_2.3.0-1chl1~trusty1_all.deb ...
Unpacking python-requests (2.3.0-1chl1~trusty1) over (2.2.1-1ubuntu0.2) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Setting up python-chardet (2.2.1-4chl1~trusty1) ...
Setting up python-requests (2.3.0-1chl1~trusty1) ...
gpg:
keyring `/tmp/tmp1zltspzd/secring.gpg' created
gpg:
keyring`/tmp/tmp1zltspzd/pubring.gpg' created
gpg:
requesting key 0E27C0A6 from hkp server keyserver.ubuntu.com
gpg:
/tmp/tmp1zltspzd/trustdb.gpg: trustdb created
gpg:
key 0E27C0A6: public key "Launchpad PPA for Salt Stack" imported
gpg:
Total number processed: 1
gpg:
              imported: 1
  (RSA: 1)

OK
- ERROR: You need to allow pip based installations (-P) in order to install the python package 'tornado >= 4.0'
  Usage :  bootstrap-salt.sh [options] <install-type> <install-type-args>
  
  Installation types:
  - stable (default)
  - stable [version](ubuntu specific)
  - daily  (ubuntu specific)
  - testing (redhat specific)
  - git
  
  Examples:
  - bootstrap-salt.sh
  - bootstrap-salt.sh stable
  - bootstrap-salt.sh stable 2014.7
  - bootstrap-salt.sh daily
  - bootstrap-salt.sh testing
  - bootstrap-salt.sh git
  - bootstrap-salt.sh git develop
  - bootstrap-salt.sh git v0.17.0
  - bootstrap-salt.sh git 8c3fadf15ec183e5ce8c63739850d543617e4357
  
  Options:
  -h  Display this message
  -v  Display script version
  -n  No colours.
  -D  Show debug output.
  -c  Temporary configuration directory
  -g  Salt repository URL. (default: git://github.com/saltstack/salt.git)
  -G  Instead of cloning from git://github.com/saltstack/salt.git, clone from https://github.com/saltstack/salt.git (Usually necessary on systems which have the regular git protocol port blocked, where https usually is not)
  -k  Temporary directory holding the minion keys which will pre-seed
      the master.
  -s  Sleep time used when waiting for daemons to start, restart and when checking
      for the services running. Default: 10
  -M  Also install salt-master
  -S  Also install salt-syndic
  -N  Do not install salt-minion
  -X  Do not start daemons after installation
  -C  Only run the configuration function. This option automatically
      bypasses any installation.
  -P  Allow pip based installations. On some distributions the required salt
      packages or its dependencies are not available as a package for that
      distribution. Using this flag allows the script to use pip as a last
      resort method. NOTE: This only works for functions which actually
      implement pip based installations.
  -F  Allow copied files to overwrite existing(config, init.d, etc)
  -U  If set, fully upgrade the system prior to bootstrapping salt
  -K  If set, keep the temporary files in the temporary directories specified
      with -c and -k.
  -I  If set, allow insecure connections while downloading any files. For
      example, pass '--no-check-certificate' to 'wget' or '--insecure' to 'curl'
  -A  Pass the salt-master DNS name or IP. This will be stored under
      /etc/salt/minion.d/99-master-address.conf
  -i  Pass the salt-minion id. This will be stored under
      /etc/salt/minion_id
  -L  Install the Apache Libcloud package if possible(required for salt-cloud)
  -p  Extra-package to install while installing salt dependencies. One package
      per -p flag. You're responsible for providing the proper package name.
  -d  Disable check_service functions. Setting this flag disables the
      'install_<distro>_check_services' checks. You can also do this by
      touching /tmp/disable_salt_checks on the target host. Defaults ${BS_FALSE}
  -H  Use the specified http proxy for the installation
  -Z  Enable external software source for newer ZeroMQ(Only available for RHEL/CentOS/Fedora based distributions)
  The following SSH command responded with a non-zero exit status.
  Vagrant assumes that this means the command failed!

/tmp/bootstrap_salt.sh  -k /tmp/minion-seed-keys -M -N stable

Stdout from the command:
-  INFO:  sh -- Version 2015.07.22
-  INFO: System Information:
-  INFO:   CPU:          GenuineIntel
-  INFO:   CPU Arch:     x86_64
-  INFO:   OS Name:      Linux
-  INFO:   OS Version:   3.13.0-55-generic
-  INFO:   Distribution: Ubuntu 14.04
-  INFO: Installing master
-  INFO: Found function install_ubuntu_stable_deps
-  INFO: Found function preseed_master
-  INFO: Found function install_ubuntu_stable
-  INFO: Found function install_ubuntu_restart_daemons
-  INFO: Found function daemons_running
-  INFO: Found function install_ubuntu_check_services
-  INFO: Running install_ubuntu_stable_deps()
  Ign http://archive.ubuntu.com trusty InRelease
  Ign http://security.ubuntu.com trusty-security InRelease
  Ign http://archive.ubuntu.com trusty-updates InRelease
  Hit http://archive.ubuntu.com trusty Release.gpg
  Get:1 http://security.ubuntu.com trusty-security Release.gpg [933 B]
  Get:2 http://archive.ubuntu.com trusty-updates Release.gpg [933 B]
  Get:3 http://security.ubuntu.com trusty-security Release [63.5 kB]
  Hit http://archive.ubuntu.com trusty Release
  Get:4 http://archive.ubuntu.com trusty-updates Release [63.5 kB]
  Get:5 http://security.ubuntu.com trusty-security/main Sources [88.7 kB]
  Get:6 http://archive.ubuntu.com trusty/main Sources [1,064 kB]
  Get:7 http://security.ubuntu.com trusty-security/universe Sources [28.1 kB]
  Get:8 http://security.ubuntu.com trusty-security/main amd64 Packages [315 kB]
  Get:9 http://security.ubuntu.com trusty-security/universe amd64 Packages [111 kB]
  Get:10 http://security.ubuntu.com trusty-security/main Translation-en [169 kB]
  Get:11 http://security.ubuntu.com trusty-security/universe Translation-en [64.0 kB]
  Get:12 http://archive.ubuntu.com trusty/universe Sources [6,399 kB]
  Hit http://archive.ubuntu.com trusty/main amd64 Packages
  Hit http://archive.ubuntu.com trusty/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty/main Translation-en
  Hit http://archive.ubuntu.com trusty/universe Translation-en
  Get:13 http://archive.ubuntu.com trusty-updates/main Sources [223 kB]
  Get:14 http://archive.ubuntu.com trusty-updates/universe Sources [127 kB]
  Get:15 http://archive.ubuntu.com trusty-updates/main amd64 Packages [584 kB]
  Get:16 http://archive.ubuntu.com trusty-updates/universe amd64 Packages [297 kB]
  Get:17 http://archive.ubuntu.com trusty-updates/main Translation-en [281 kB]
  Get:18 http://archive.ubuntu.com trusty-updates/universe Translation-en [157 kB]
  Ign http://archive.ubuntu.com trusty/main Translation-en_US
  Ign http://archive.ubuntu.com trusty/universe Translation-en_US
  Fetched 10.0 MB in 1min 9s (144 kB/s)
  Reading package lists...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  The following NEW packages will be installed:
  debian-archive-keyring
  0 upgraded, 1 newly installed, 0 to remove and 52 not upgraded.
  Need to get 34.4 kB of archives.
  After this operation, 84.0 kB of additional disk space will be used.
  Get:1 http://archive.ubuntu.com/ubuntu/ trusty/universe debian-archive-keyring all 2012.4 [34.4 kB]
  Fetched 34.4 kB in 1s (30.0 kB/s)
  Selecting previously unselected package debian-archive-keyring.
  (Reading database ... 86712 files and directories currently installed.)
  Preparing to unpack .../debian-archive-keyring_2012.4_all.deb ...
  Unpacking debian-archive-keyring (2012.4) ...
  Setting up debian-archive-keyring (2012.4) ...
  Ign http://security.ubuntu.com trusty-security InRelease
  Ign http://archive.ubuntu.com trusty InRelease
  Hit http://security.ubuntu.com trusty-security Release.gpg
  Ign http://archive.ubuntu.com trusty-updates InRelease
  Hit http://security.ubuntu.com trusty-security Release
  Hit http://archive.ubuntu.com trusty Release.gpg
  Hit http://archive.ubuntu.com trusty-updates Release.gpg
  Hit http://security.ubuntu.com trusty-security/main Sources
  Hit http://archive.ubuntu.com trusty Release
  Hit http://security.ubuntu.com trusty-security/universe Sources
  Hit http://archive.ubuntu.com trusty-updates Release
  Hit http://security.ubuntu.com trusty-security/main amd64 Packages
  Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty/main Sources
  Hit http://archive.ubuntu.com trusty/universe Sources
  Hit http://security.ubuntu.com trusty-security/main Translation-en
  Hit http://archive.ubuntu.com trusty/main amd64 Packages
  Hit http://security.ubuntu.com trusty-security/universe Translation-en
  Hit http://archive.ubuntu.com trusty/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty/main Translation-en
  Hit http://archive.ubuntu.com trusty/universe Translation-en
  Hit http://archive.ubuntu.com trusty-updates/main Sources
  Hit http://archive.ubuntu.com trusty-updates/universe Sources
  Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
  Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty-updates/main Translation-en
  Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
  Ign http://archive.ubuntu.com trusty/main Translation-en_US
  Ign http://archive.ubuntu.com trusty/universe Translation-en_US
  Reading package lists...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  software-properties-common is already the newest version.
  0 upgraded, 0 newly installed, 0 to remove and 52 not upgraded.
-  INFO: Installing Python Requests/Chardet from Chris Lea's PPA repository
  gpg: keyring `/tmp/tmpq__j495u/secring.gpg' created
  gpg: keyring`/tmp/tmpq__j495u/pubring.gpg' created
  gpg: requesting key C7917B12 from hkp server keyserver.ubuntu.com
  gpg: /tmp/tmpq__j495u/trustdb.gpg: trustdb created
  gpg: key C7917B12: public key "Launchpad chrislea" imported
  gpg: Total number processed: 1
  gpg:               imported: 1  (RSA: 1)
  OK
  gpg: keyring `/tmp/tmpyz5u8lys/secring.gpg' created
  gpg: keyring`/tmp/tmpyz5u8lys/pubring.gpg' created
  gpg: requesting key C7917B12 from hkp server keyserver.ubuntu.com
  gpg: /tmp/tmpyz5u8lys/trustdb.gpg: trustdb created
  gpg: key C7917B12: public key "Launchpad chrislea" imported
  gpg: Total number processed: 1
  gpg:               imported: 1  (RSA: 1)
  OK
  Ign http://security.ubuntu.com trusty-security InRelease
  Ign http://archive.ubuntu.com trusty InRelease
  Ign http://ppa.launchpad.net trusty InRelease
  Hit http://security.ubuntu.com trusty-security Release.gpg
  Ign http://archive.ubuntu.com trusty-updates InRelease
  Hit http://security.ubuntu.com trusty-security Release
  Ign http://ppa.launchpad.net trusty InRelease
  Hit http://archive.ubuntu.com trusty Release.gpg
  Hit http://security.ubuntu.com trusty-security/main Sources
  Hit http://archive.ubuntu.com trusty-updates Release.gpg
  Hit http://security.ubuntu.com trusty-security/universe Sources
  Get:1 http://ppa.launchpad.net trusty Release.gpg [316 B]
  Hit http://security.ubuntu.com trusty-security/main amd64 Packages
  Hit http://archive.ubuntu.com trusty Release
  Get:2 http://ppa.launchpad.net trusty Release.gpg [316 B]
  Hit http://security.ubuntu.com trusty-security/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty-updates Release
  Get:3 http://ppa.launchpad.net trusty Release [14.0 kB]
  Hit http://security.ubuntu.com trusty-security/main Translation-en
  Hit http://archive.ubuntu.com trusty/main Sources
  Hit http://security.ubuntu.com trusty-security/universe Translation-en
  Get:4 http://ppa.launchpad.net trusty Release [14.0 kB]
  Hit http://archive.ubuntu.com trusty/universe Sources
  Get:5 http://ppa.launchpad.net trusty/main amd64 Packages [1,041 B]
  Hit http://archive.ubuntu.com trusty/main amd64 Packages
  Hit http://archive.ubuntu.com trusty/universe amd64 Packages
  Get:6 http://ppa.launchpad.net trusty/main amd64 Packages [2,308 B]
  Hit http://archive.ubuntu.com trusty/main Translation-en
  Hit http://archive.ubuntu.com trusty/universe Translation-en
  Hit http://archive.ubuntu.com trusty-updates/main Sources
  Hit http://archive.ubuntu.com trusty-updates/universe Sources
  Hit http://archive.ubuntu.com trusty-updates/main amd64 Packages
  Hit http://archive.ubuntu.com trusty-updates/universe amd64 Packages
  Hit http://archive.ubuntu.com trusty-updates/main Translation-en
  Hit http://archive.ubuntu.com trusty-updates/universe Translation-en
  Ign http://ppa.launchpad.net trusty/main Translation-en_US
  Ign http://archive.ubuntu.com trusty/main Translation-en_US
  Ign http://ppa.launchpad.net trusty/main Translation-en
  Ign http://archive.ubuntu.com trusty/universe Translation-en_US
  Ign http://ppa.launchpad.net trusty/main Translation-en_US
  Ign http://ppa.launchpad.net trusty/main Translation-en
  Fetched 32.0 kB in 12s (2,521 B/s)
  Reading package lists...
  Reading package lists...
  Building dependency tree...
  Reading state information...
  pciutils is already the newest version.
  procps is already the newest version.
  python-apt is already the newest version.
  upstart is already the newest version.
  The following extra packages will be installed:
  python-chardet
  The following packages will be upgraded:
  python-chardet python-requests
  2 upgraded, 0 newly installed, 0 to remove and 51 not upgraded.
  Need to get 151 kB of archives.
  After this operation, 9,216 B disk space will be freed.
  Get:1 http://ppa.launchpad.net/chris-lea/python-chardet/ubuntu/ trusty/main python-chardet all 2.2.1-4chl1~trusty1 [107 kB]
  Get:2 http://ppa.launchpad.net/chris-lea/python-requests/ubuntu/ trusty/main python-requests all 2.3.0-1chl1~trusty1 [44.3 kB]
  Fetched 151 kB in 2s (55.4 kB/s)
  (Reading database ... 86722 files and directories currently installed.)
  Preparing to unpack .../python-chardet_2.2.1-4chl1~trusty1_all.deb ...
  Unpacking python-chardet (2.2.1-4chl1~trusty1) over (2.0.1-2build2) ...
  Preparing to unpack .../python-requests_2.3.0-1chl1~trusty1_all.deb ...
  Unpacking python-requests (2.3.0-1chl1~trusty1) over (2.2.1-1ubuntu0.2) ...
  Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
  Setting up python-chardet (2.2.1-4chl1~trusty1) ...
  Setting up python-requests (2.3.0-1chl1~trusty1) ...
  gpg: keyring `/tmp/tmp1zltspzd/secring.gpg' created
  gpg: keyring`/tmp/tmp1zltspzd/pubring.gpg' created
  gpg: requesting key 0E27C0A6 from hkp server keyserver.ubuntu.com
  gpg: /tmp/tmp1zltspzd/trustdb.gpg: trustdb created
  gpg: key 0E27C0A6: public key "Launchpad PPA for Salt Stack" imported
  gpg: Total number processed: 1
  gpg:               imported: 1  (RSA: 1)
  OK
- ERROR: You need to allow pip based installations (-P) in order to install the python package 'tornado >= 4.0'
  
  Usage :  bootstrap-salt.sh [options] <install-type> <install-type-args>
  
  Installation types:
  - stable (default)
  - stable [version](ubuntu specific)
  - daily  (ubuntu specific)
  - testing (redhat specific)
  - git
  
  Examples:
  - bootstrap-salt.sh
  - bootstrap-salt.sh stable
  - bootstrap-salt.sh stable 2014.7
  - bootstrap-salt.sh daily
  - bootstrap-salt.sh testing
  - bootstrap-salt.sh git
  - bootstrap-salt.sh git develop
  - bootstrap-salt.sh git v0.17.0
  - bootstrap-salt.sh git 8c3fadf15ec183e5ce8c63739850d543617e4357
  
  Options:
  -h  Display this message
  -v  Display script version
  -n  No colours.
  -D  Show debug output.
  -c  Temporary configuration directory
  -g  Salt repository URL. (default: git://github.com/saltstack/salt.git)
  -G  Instead of cloning from git://github.com/saltstack/salt.git, clone from https://github.com/saltstack/salt.git (Usually necessary on systems which have the regular git protocol port blocked, where https usually is not)
  -k  Temporary directory holding the minion keys which will pre-seed
      the master.
  -s  Sleep time used when waiting for daemons to start, restart and when checking
      for the services running. Default: 10
  -M  Also install salt-master
  -S  Also install salt-syndic
  -N  Do not install salt-minion
  -X  Do not start daemons after installation
  -C  Only run the configuration function. This option automatically
      bypasses any installation.
  -P  Allow pip based installations. On some distributions the required salt
      packages or its dependencies are not available as a package for that
      distribution. Using this flag allows the script to use pip as a last
      resort method. NOTE: This only works for functions which actually
      implement pip based installations.
  -F  Allow copied files to overwrite existing(config, init.d, etc)
  -U  If set, fully upgrade the system prior to bootstrapping salt
  -K  If set, keep the temporary files in the temporary directories specified
      with -c and -k.
  -I  If set, allow insecure connections while downloading any files. For
      example, pass '--no-check-certificate' to 'wget' or '--insecure' to 'curl'
  -A  Pass the salt-master DNS name or IP. This will be stored under
      /etc/salt/minion.d/99-master-address.conf
  -i  Pass the salt-minion id. This will be stored under
      /etc/salt/minion_id
  -L  Install the Apache Libcloud package if possible(required for salt-cloud)
  -p  Extra-package to install while installing salt dependencies. One package
      per -p flag. You're responsible for providing the proper package name.
  -d  Disable check_service functions. Setting this flag disables the
      'install_<distro>_check_services' checks. You can also do this by
      touching /tmp/disable_salt_checks on the target host. Defaults ${BS_FALSE}
  -H  Use the specified http proxy for the installation
  -Z  Enable external software source for newer ZeroMQ(Only available for RHEL/CentOS/Fedora based distributions)

Stderr from the command:

stdin: is not a tty
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  204k  100  204k    0     0  87900      0  0:00:02  0:00:02 --:--:-- 87871

bash-3.2# 

---

**Comment by qszhusightp** [comment]
New to salt and having the same issue. Seem to be caused by a recent update of the salt bootstrap script. See: mitchellh/vagrant#6029

Then bumping into the issue here: mitchellh/vagrant#5973, had to downgrade vagrant to 1.7.2

Hope that helps.

**Comment by rduggal** [comment]
I managed to get the script with wget and run it with a -P to complete install. Closing issue

**Comment by rduggal** [comment]
Resolved

**Comment by jpduckwo** [comment]
Vagrantfile should be updated for each machine as follows to resolve

```
      salt.bootstrap_options = "-P"
```

Also only use Vagrant v 1.7.2 for the moment as there is an issue setting config files for minions in 1.7.4

**Comment by thornycrackers** [comment]
@jpduckwo Thankyou, That fixed my issues with it!
